### ISSUE TITLE
Should we need to put vendor's thing in repo?

### ISSUE THREAD

**Issue by chonla** [gogetth/sscard#1]
As it mentioned in `func.go`, I think you can remove vendor directory and use `go get ./...` to retrieve it.

**Comment by Napat** [comment]
Thank you very much for your question. 

In my opinion there is no right answer for this question.

Refer to article: 
https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory

```
# Should I commit my vendor directory?

It's up to you:

## Pros

- It's the only way to get truly reproducible builds, as it guards against upstream renames, deletes and commit history overwrites.

- You don't need an extra dep ensure step to sync vendor/ with Gopkg.lock after most operations, such as go get, cloning, getting latest, merging, etc.

## Cons
- Your repo will be bigger, potentially a lot bigger, though prune can help minimize this problem.

- PR diffs will include changes for files under vendor/ when Gopkg.lock is modified, however files in vendor/ are hidden by default on GitHub.
```

In this project everything in vendor, `github.com/ebfe/scard`,  is just the text and very little memory cost. 
And to be sure we'll have dependency even the original source is unavailable or some major history changing.  

By the way any developers who pull this repository will not have to confuse with any vendoring tool, dependencies or extra commands. 

In this case I prefer committing the vendor in sscard repository more than `go get ./...` to retrieve it.
