### ISSUE TITLE
Should we rename "Transmiter" interface to "Transmitter"?

### ISSUE THREAD

**Issue by nattawitc** [gogetth/sscard#4]
According to effective go

> By convention, one-method interfaces are named by the method name plus an -er suffix or similar modification to construct an agent noun.

That's why interface with "Transmit" method is named "Transmiter" but goreport found this as a misspell of "Transmitter" and lower the reported percentage. Should we fix this?

**Comment by chonla** [comment]
Yes.

**Comment by Napat** [comment]
Absolutely.
"Transmiter" is a misspelled word and should replaced by "Transmitter".  
Referenced to [net standard package: timeoutTransmitter()](https://golang.org/src/net/mockserver_test.go?h=Transmit).
